version: '3.1'

services:

  mongo:
    image: mongo-express
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: abchkro@gmail.com
      MONGO_INITDB_ROOT_PASSWORD: abel2004

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 3000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: abchkro
      ME_CONFIG_MONGODB_ADMINPASSWORD: abel2004
      ME_CONFIG_MONGODB_URL: mongodb+srv://abchkro:abel2004@cluster0.qfqjgfo.mongodb.net/Tfg
      ME_CONFIG_BASICAUTH: false